version: '3'
services:
  # myapplication:
  #   image: myapp:1.0
  #   environment: 
  #     - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
  #   ports:
  #     - 3000:3000
  mongodb:
    image: mongo
    container_name: db_mongo
    volumes:
      - /var/model/mongodb:/data/model
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chj
      - MONGO_INITDB_ROOT_PASSWORD=hongchenjin
    ports:
      - 27017:27017
    networks:
      - backend-model

networks:
  backend-model:
    external: true