FROM golang:1.18

WORKDIR /dataCenter
# china mirror
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
RUN go build -o dataCenter main.go
VOLUME [ "/dataCenter/store" ]
CMD [ "./dataCenter" ]
